# ============================================================
# POSTGRESQL - NEON
# ============================================================
#db.url=jdbc:postgresql://ep-restless-hall-aehwldwn-pooler.c-2.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.url=jdbc:postgresql://ep-wandering-river-b5b0i7i9-pooler.c-7.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require

db.username=neondb_owner
db.password=npg_2EcwCu8KOlPz
# ============================================================
# DDL
# ============================================================
db.ddl.auto=false
db.ddl.script=schema_sv.sql